### ISSUE TITLE
Next-episode throws an error on install or enable with Nexus

### ISSUE THREAD

**Issue by Clumpton** [santah/next-episode-kodi#6]
Problem already reported on nextè-episode forum, was sent here.
This started when I moved to Nexus 20.0 Beta2 (previously worked OK on Maven's Nexus Dolby Vision fork)
Running on Nvidia Shield Pro 2019.
Android TV 11.0.0 Api Level 30
Kodi 21.0 Beta2 2023-12-10

An error is thrown on installing next-episode, it installs but does not work.
Trying to disable/enable causes the same error, viz:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                   EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'six'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.next-episode/service.py", line 8, in <module>
                                                       from libs.exception_logger import log_exception
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.next-episode/libs/exception_logger.py", line 24, in <module>
                                                       import six
                                                   ModuleNotFoundError: No module named 'six'
                                                   -->End of Python script error report<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'six'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.next-episode/service.py", line 8, in <module>
                                                       from libs.exception_logger import log_exception
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.next-episode/libs/exception_logger.py", line 24, in <module>
                                                       import six
                                                   ModuleNotFoundError: No module named 'six'
                                                   -->End of Python script error report<--
```

Have tried removing and, re-installing python six - no joy.
Dropped a copy of six.py in app and lib folders of next-episode add-on, no joy either.

Found a (very poor) workaround and managed to get the add-on installed and working by a huge kludge. I have commented out line 24 in exception_logger.py so that it does not try to import "six".
This allows the add-on to be enabled but obviously will throw an error every time exception_logger.py tries to use functions from "six" (six.iteritems and six.text_type).
SIx is showing as installed in the kodi system add-ons manager.
There only appears to be 3 instance where these functions are used, maybe a manual "if PY3:" in the code could easily solve this and remove the dependency on a module that doesn't seem to want to be found?
Thanks in advance for any light you can shed on this problem.

**Comment by romanvm** [comment]
The obvious solution would be to remove Python 2 compatibility completely. But it's strange that six library does not work on Nexus.
